# Re-export every groups schema from the application layer.
# Router imports and the wire format are unchanged.
from app.modules.groups.application.schemas import (  # noqa: F401
    GroupViewSignal,
    GroupCreate,
    GroupUpdate,
    GroupPermissionsUpdate,
    AddMembersRequest,
    ReportGroupRequest,
    GroupOut,
    GroupMemberOut,
    GroupSuggestionOut,
    InviteLinkOut,
    GroupListOut,
    GroupMembersPageOut,
    GroupMediaOut,
    GroupMediaUploadOut,
    GroupJoinRequestOut,
    GroupJoinRequestListOut,
    AdminPendingRequestOut,
    AdminPendingRequestsListOut,
    GroupDealCreate,
    GroupDealUpdate,
    GroupDealResponse,
    GroupDealPublishRequest,
    GroupDealListOut,
)

__all__ = [
    "GroupViewSignal",
    "GroupCreate",
    "GroupUpdate",
    "GroupPermissionsUpdate",
    "AddMembersRequest",
    "ReportGroupRequest",
    "GroupOut",
    "GroupMemberOut",
    "GroupSuggestionOut",
    "InviteLinkOut",
    "GroupListOut",
    "GroupMembersPageOut",
    "GroupMediaOut",
    "GroupMediaUploadOut",
    "GroupJoinRequestOut",
    "GroupJoinRequestListOut",
    "AdminPendingRequestOut",
    "AdminPendingRequestsListOut",
    "GroupDealCreate",
    "GroupDealUpdate",
    "GroupDealResponse",
    "GroupDealPublishRequest",
    "GroupDealListOut",
]
