"""news_new raw + enriched articles

Revision ID: 1373b3c3b0de
Revises: m4n5o6p7q8r9
Create Date: 2026-06-22 15:12:35.126399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1373b3c3b0de'
down_revision: Union[str, None] = 'm4n5o6p7q8r9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_raw_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('article_url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_country', sa.String(length=80), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('api_summary', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intelligence_status', sa.String(length=20), nullable=False),
    sa.Column('platform_arrived_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_news_raw_articles_arrived_at', 'news_raw_articles', ['platform_arrived_at'], unique=False)
    op.create_index('ix_news_raw_articles_published_at', 'news_raw_articles', ['published_at'], unique=False)
    op.create_index('ix_news_raw_articles_status', 'news_raw_articles', ['intelligence_status'], unique=False)
    op.create_table('news_enriched_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_article_id', sa.UUID(), nullable=False),
    sa.Column('primary_factor', sa.String(length=40), nullable=False),
    sa.Column('factor_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_category', sa.String(length=20), nullable=False),
    sa.Column('summary_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_long', sa.Text(), nullable=True),
    sa.Column('impact_direction', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('impact_factor', sa.String(length=120), nullable=True),
    sa.Column('impact_explanation', sa.Text(), nullable=True),
    sa.Column('role_trader', sa.Float(), nullable=False),
    sa.Column('role_broker', sa.Float(), nullable=False),
    sa.Column('role_exporter', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['news_raw_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_article_id')
    )
    # NOTE: autogenerate also surfaced pre-existing drift on unrelated tables
    # (group_deals/personal_deals/chat_attachments/messages/embeddings indexes).
    # Stripped intentionally — this migration only creates the news_new tables.


def downgrade() -> None:
    op.drop_table('news_enriched_articles')
    op.drop_index('ix_news_raw_articles_status', table_name='news_raw_articles')
    op.drop_index('ix_news_raw_articles_published_at', table_name='news_raw_articles')
    op.drop_index('ix_news_raw_articles_arrived_at', table_name='news_raw_articles')
    op.drop_table('news_raw_articles')
    # ### end Alembic commands ###
