"""add is_government to news_enriched_articles

Revision ID: 2e5f1a7c9b40
Revises: n5o6p7q8r9s0
Create Date: 2026-06-23

Hand-written (not autogenerated) to avoid re-surfacing pre-existing drift on
unrelated tables. Additive, non-destructive: one boolean column defaulting to
false so existing rows backfill safely.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2e5f1a7c9b40'
down_revision: Union[str, None] = 'n5o6p7q8r9s0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'news_enriched_articles',
        sa.Column('is_government', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    op.drop_column('news_enriched_articles', 'is_government')
