"""
Domain entities for the news module.

Pure Python dataclasses — no SQLAlchemy, no Pydantic, no FastAPI.
Every field maps 1:1 to a column in data/models.py; the repository
translates between these and ORM rows.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from app.modules.news.domain.value_objects import IntelligenceStatus


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Ingestion ─────────────────────────────────────────────────────────────────

@dataclass
class RawArticle:
    """
    A news article exactly as received from the provider, normalised into a
    provider-agnostic shape. One row per unique external_id (dedup key).
    Intelligence reads these and writes a paired EnrichedArticle.
    """
    # Required on creation
    external_id:        str
    title:              str
    article_url:        str

    # Set by the provider adapter
    id:                 UUID                = field(default_factory=uuid.uuid4)
    description:        Optional[str]       = None
    content:            Optional[str]       = None      # may be truncated by provider
    image_url:          Optional[str]       = None
    published_at:       datetime            = field(default_factory=_utcnow)
    language:           Optional[str]       = None
    source_name:        Optional[str]       = None
    source_url:         Optional[str]       = None
    source_country:     Optional[str]       = None      # ISO country bias used at fetch time
    authors:            list[str]           = field(default_factory=list)
    is_duplicate:       bool                = False
    api_summary:        Optional[str]       = None      # provider's own summary (verbatim)
    raw_metadata:       Optional[dict]      = None      # full provider payload for audit/replay

    # Set by the ingestion pipeline
    intelligence_status: IntelligenceStatus = IntelligenceStatus.PENDING
    platform_arrived_at: datetime           = field(default_factory=_utcnow)
    is_active:           bool               = True
    created_at:          datetime           = field(default_factory=_utcnow)
    updated_at:          datetime           = field(default_factory=_utcnow)


# ── Intelligence ──────────────────────────────────────────────────────────────

@dataclass
class EnrichedArticle:
    """
    The enriched view of a RawArticle — one row per RawArticle.
    All fields are produced by the LLM pipeline except role_* which are
    pre-computed from the RELEVANCY_MATRIX at enrichment time.
    """
    # Required
    raw_article_id:     UUID
    primary_factor:     str                 # one of the 10 taxonomy slugs
    geo_category:       str                 # "global" | "domestic"
    impact_direction:   str                 # "positive" | "neutral" | "negative"
    impact_score:       float               # 0–10
    role_trader:        float               # pre-computed from RELEVANCY_MATRIX
    role_broker:        float
    role_exporter:      float

    # Generated by pipeline
    id:                 UUID                = field(default_factory=uuid.uuid4)
    is_government:      bool                = False
    factor_scores:      Optional[list]      = None      # [{factor, score}], top 2-3
    commodity_tags:     Optional[list]      = None      # ["rice", "cotton", ...]
    state_tags:         Optional[list]      = None      # ["Punjab", "Maharashtra", ...]
    location_city:      Optional[str]       = None      # LLM-extracted primary place
    location_state:     Optional[str]       = None
    latitude:           Optional[float]     = None      # supplementary, best-effort
    longitude:          Optional[float]     = None
    summary_bullets:    Optional[list]      = None      # ["...", "...", "..."]
    summary_long:       Optional[str]       = None
    impact_factor:      Optional[str]       = None      # short label, e.g. "export ban"
    impact_explanation: Optional[str]       = None      # one-sentence explanation
    model_version:      Optional[str]       = None
    generated_at:       datetime            = field(default_factory=_utcnow)
    created_at:         datetime            = field(default_factory=_utcnow)


# ── Interactions ──────────────────────────────────────────────────────────────

@dataclass
class NewsInteractionEvent:
    """
    One interaction signal from the client or server.
    Client events: impression, dwell, open_article, share_tap.
    Server events: revisit (generated when open_article is a re-open).
    """
    profile_id:     int
    article_id:     UUID
    event_type:     str

    id:             int                 = 0          # 0 = not yet persisted
    value_ms:       Optional[int]       = None       # dwell duration
    occurred_at:    datetime            = field(default_factory=_utcnow)
    created_at:     datetime            = field(default_factory=_utcnow)
    processed_at:   Optional[datetime]  = None


@dataclass
class NewsView:
    """
    One row per (profile_id, article_id). Tracks open count and first/last seen.
    The repository uses this for revisit detection: if a row already exists,
    the current open_article event is a revisit.
    """
    profile_id:         int
    article_id:         UUID

    id:                 int         = 0
    view_count:         int         = 1
    first_viewed_at:    datetime    = field(default_factory=_utcnow)
    last_viewed_at:     datetime    = field(default_factory=_utcnow)


@dataclass
class NewsLike:
    profile_id:     int
    article_id:     UUID

    id:             int         = 0
    created_at:     datetime    = field(default_factory=_utcnow)


@dataclass
class NewsSave:
    profile_id:     int
    article_id:     UUID

    id:             int         = 0
    created_at:     datetime    = field(default_factory=_utcnow)


@dataclass
class NewsShare:
    """
    Covers both external shares (WhatsApp, copy-link) and in-app sends.
    platform=None means in-app send; platform="whatsapp" etc. means external.
    """
    profile_id:     int
    article_id:     UUID

    id:             int             = 0
    platform:       Optional[str]   = None
    created_at:     datetime        = field(default_factory=_utcnow)


@dataclass
class NewsArticleStats:
    """
    Pre-computed per-article counters, updated incrementally via adjust_article_stats().
    One row per article — O(1) lookup at feed-card assembly time.
    """
    article_id:     UUID
    view_count:     int         = 0
    like_count:     int         = 0
    save_count:     int         = 0
    share_count:    int         = 0
    updated_at:     datetime    = field(default_factory=_utcnow)


# ── Taste ─────────────────────────────────────────────────────────────────────

@dataclass
class UserNewsTaste:
    """
    One row per (profile_id, dimension_type, dimension_key).
    dimension_type ∈ {category, source, tag}.
    dimension_key is the specific value, e.g. "price_volatility" or "The Hindu".
    Scores accumulate over time and are decayed at read time by taste_service.
    """
    profile_id:         int
    dimension_type:     str
    dimension_key:      str
    positive_score:     float       = 0.0
    negative_score:     float       = 0.0
    event_count:        int         = 0
    last_event_at:      datetime    = field(default_factory=_utcnow)


@dataclass
class UserNewsTasteProfile:
    """
    Rolled-up taste summary per profile. Bootstrapped once TASTE_BOOTSTRAP_EVENTS
    events are accumulated. Planned feature — not yet used by the recommendation
    engine but the table and entity are reserved for Layer 3 scoring.
    """
    profile_id:         int
    total_events:       int             = 0
    bootstrapped:       bool            = False
    dominant_factor:    Optional[str]   = None      # highest-weight category key
    factor_weights:     Optional[dict]  = None      # {factor_slug: normalised_weight}
    updated_at:         datetime        = field(default_factory=_utcnow)


# ── Trending ──────────────────────────────────────────────────────────────────

@dataclass
class NewsTrending:
    """
    Velocity-ranked trending snapshot. Recomputed by recommendation/jobs/recalc_trending.py.
    Schema is platform-wide for now; Decision 3 (per-segment) will extend this
    with a segment_id field once the base module is stable.
    """
    article_id:         UUID
    velocity_score:     float       = 0.0
    unique_profiles:    int         = 0
    computed_at:        datetime    = field(default_factory=_utcnow)


# ── Recommendation cache ──────────────────────────────────────────────────────

@dataclass
class FeedRankingCache:
    """
    Cached ordered list of article UUIDs for a given (profile, feed_type).
    TTL = CACHE_TTL_HOURS (2h). Invalidated on taste change.
    """
    profile_id:             int
    feed_type:              str
    ranked_article_ids:     list[UUID]
    computed_at:            datetime
    expires_at:             datetime

    id:                     UUID    = field(default_factory=uuid.uuid4)


# ── Feed output (value objects, not persisted) ────────────────────────────────

@dataclass
class NewsCard:
    """
    The display card for one article in any feed.
    Assembled by recommendation/engine.py from RawArticle + EnrichedArticle + stats.
    """
    article_id:         UUID
    title:              str
    platform_arrived_at: datetime
    time_on_platform:   str         # human-readable, e.g. "3h ago"

    image_url:          Optional[str]   = None
    source_name:        Optional[str]   = None
    summary_bullets:    Optional[list]  = None
    primary_factor:     Optional[str]   = None
    geo_category:       Optional[str]   = None
    is_government:      bool            = False
    impact_direction:   Optional[str]   = None
    impact_score:       Optional[float] = None
    like_count:         int             = 0
    share_count:        int             = 0
    is_liked:           bool            = False
    is_saved:           bool            = False


@dataclass
class NewsCardDetail(NewsCard):
    """Full article detail view — superset of NewsCard."""
    description:        Optional[str]   = None
    article_url:        str             = ""
    source_url:         Optional[str]   = None
    published_at:       Optional[datetime] = None
    impact_explanation: Optional[str]   = None
    impact_factor:      Optional[str]   = None
    factor_scores:      Optional[list]  = None
    view_count:         Optional[int]   = None
    save_count:         Optional[int]   = None


@dataclass
class NewsFeedPage:
    """
    Paginated feed result returned by all feed endpoints.
    next_cursor is the article_id string of the last article in this page;
    pass it as cursor_article_id on the next request to get the next page.
    None means this is the last page.
    """
    articles:       list[NewsCard]      = field(default_factory=list)
    next_cursor:    Optional[str]       = None
